spring:
  application:
    name: single-line-diagram-server

  mvc:
    async:
      # To have the same behavior of no timeouts as regular endpoints for servlet 3.0+ asynccontext endpoints
      # Can be removed when set as default in our common ws config
      request-timeout: -1

gridsuite:
  services:
    -
      name: geo-data-server
      base-uri: http://geo-data-server/

powsybl-ws:
  database:
    name: diagram

# 3 maximum concurrent Network Area Diagram generations for the current configuration
max-concurrent-nad-generations: 3

diagram-server:
  nad:
    max-voltage-levels: 1600
