server:
  port: 5005

powsybl:
  services:
    network-store-server:
      base-uri: http://localhost:8080

gridsuite:
  services:
      geo-data-server:
        base-uri: http://localhost:8087

powsybl-ws:
  database:
    host: localhost
