spring:
  application:
    name: single-line-diagram-server

springdoc:
  swagger-ui:
    path: swagger-ui.html

server:
  port: 5005
  forward-headers-strategy: framework

network-store-server:
  base-uri: http://localhost:8080
