name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-backend-app-generic.yml@8e990dd28cbccff180f322903ac1e3131ab3632a
    with:
      dockerImage: docker.io/powsybl/single-line-diagram-server
      dockerUsername: powsyblci
      eventOrganizations: gridsuite
      eventType: single_line_diagram_server_updated
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      docker-token: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
