name: Docker Deploy

on: workflow_dispatch

jobs:
  run-deploy:
    uses: powsybl/github-ci/.github/workflows/manual-dockerdeploy-backend-app-generic.yml@c0849fd1236966d31e8f7167ec5beab4517bbf28
    with:
      dockerImage: docker.io/powsybl/single-line-diagram-server
      dockerUsername: powsyblci
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
