name: SonarCloud Analysis on Tag Push

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/sonarcloud-maven-tag-analysis.yml@c0849fd1236966d31e8f7167ec5beab4517bbf28
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}